# On any merge to the trunk branch, bumps the semantic version number
# and pushes that tag back to the GitHub repo
name: Build

on:
  push:
    branches:
      - trunk
    paths:
      - "**/*.tf"
      - ".github/workflows/*"

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'hplogsdon' && !contains(github.event.head_commit.message, '[no-ci]')

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: '0'

      - name: Bump Version number
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          noVersionBumpBehavior: 'patch'
          branch: ${{ github.ref_name }}

      - name: Create tag ${{ steps.semver.outputs.next }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver.outputs.next }}",
              sha: "${{ github.sha }}"
            })