name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hplogsdon'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get PR label
        uses: actions-ecosystem/action-release-label@v1
        id: release_label
        if: ${{ github.event.pull_request.merged == true }}

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: last_tag
        if: ${{ steps.release_label.outputs.level != null }}
        with:
          semver_only: true

      - name: Bump Semver
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        if: ${{ steps.release_label.outputs.level != null }}
        with:
          current_version: ${{ steps.last_tag.outputs.tag }}
          level: ${{ steps.last_tag.outputs.level }}

      - name: Push Tag
        uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.last_tag.outputs.level != null }}
        with:
          tag: ${{ steps.bump_semver.outputs.new_version }}
          message: '${{ steps.bump_semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - name: gh::release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_semver.outputs.new_version }}
