name: Release

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  push:
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: '0'

      - run: |
          LATEST_TAG=$(git describe --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          tag: ${{ env.LATEST_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: true
          excludeTypes: 'build,docs,style'
          useGitmojis: false

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit CHANGELOG.md
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.workflow_run.head_sha || 'trunk' }}
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
