name: Release

on:
  push:
    branches:
      - trunk
      - master
    paths:
      - "**/*.tf"
      - ".github/workflows/*"

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hplogsdon'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: '0'

      - name: Bump Version number
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          noVersionBumpBehavior: 'patch'
          branch: 'trunk'

      - name: Create tag ${{ steps.semver.outputs.next }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver.outputs.next }}",
              sha: context.sha
            })

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.semver.outputs.next }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: true

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          commit: ${{ github.event.workflow_run.head_sha || 'trunk' }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.workflow_run.head_sha || 'trunk' }}
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md