name: Tag

on:
  push:
    branches:
      - trunk
      - master
    paths:
      - "**/*.tf"
      - ".github/workflows/*"

permissions:
  contents: read
  pull-requests: write
  repository-projects: write

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hplogsdon'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: '0'

      - id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.workflow_run.head_sha || 'trunk' }}

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.semver.outputs.current }}
          toTag: ${{ steps.semver.outputs.next }}
          writeToFile: true

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          commit: ${{ github.event.workflow_run.head_sha || 'trunk' }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create tag
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            github.rest.git.createRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: "refs/tags/${{ steps.format.outputs.semver }}",
#              sha: context.sha
#            })