name: Tag

on:
  push:
    branches:
      - trunk
      - master
    paths:
      - "**/*.tf"
      - ".github/workflows/*"

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hplogsdon'
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "trunk-based"
          prefix: "v"
          prerelease_id: "pre"
          main_branch_name: "trunk"
          develop_branch_name: "develop"

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ !steps.semver-tag.outputs.is_prerelease }}
        with:
          tag: ${{ steps.semver-tag.outputs.semver_tag }}
          message: '${{ steps.semver-tag.outputs.semver_tag }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
